#!/usr/bin/env python3
"""Generate docs/MCP_TOOLS.md from the registered FastMCP tools.

Walks every `@mcp.tool`-decorated function, groups by module, and emits a
markdown catalogue. Run from the repo root:

    python scripts/gen_tool_docs.py

Output: docs/MCP_TOOLS.md (overwritten).
"""

from __future__ import annotations

import asyncio
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

import cutmaster_ai  # noqa: F401, E402 — triggers tool registration
from cutmaster_ai.config import mcp  # noqa: E402


def _first_sentence(doc: str | None) -> str:
    if not doc:
        return ""
    line = doc.strip().split("\n")[0].strip()
    return line.rstrip(".") + "." if line else ""


def _module_label(module: str) -> str:
    """Turn ``cutmaster_ai.tools.color`` → ``tools/color.py``."""
    parts = module.split(".")
    if parts[0] == "cutmaster_ai":
        parts = parts[1:]
    return "/".join(parts) + ".py"


async def main() -> None:
    tools = await mcp.list_tools()

    by_module: dict[str, list[tuple[str, str]]] = defaultdict(list)
    for tool in tools:
        module = getattr(tool, "module", None) or getattr(tool.fn, "__module__", "unknown")
        doc = _first_sentence(getattr(tool, "description", None) or tool.fn.__doc__)
        by_module[module].append((tool.name, doc))

    lines: list[str] = []
    lines.append("# MCP Tool Catalogue")
    lines.append("")
    lines.append(f"_Auto-generated by `scripts/gen_tool_docs.py` — {len(tools)} tools total._")
    lines.append("")
    lines.append(
        "Every tool is prefixed `cutmaster_` and returns a string "
        "(error text or JSON / success message). Tools are grouped by the module "
        "that registers them — see [ARCHITECTURE.md](ARCHITECTURE.md) for the "
        "responsibility model."
    )
    lines.append("")

    for module in sorted(by_module):
        lines.append(f"## `{_module_label(module)}`")
        lines.append("")
        lines.append("| Tool | Description |")
        lines.append("|---|---|")
        for name, doc in sorted(by_module[module]):
            lines.append(f"| `{name}` | {doc} |")
        lines.append("")

    out = ROOT / "docs" / "MCP_TOOLS.md"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {out} — {len(tools)} tools across {len(by_module)} modules")


if __name__ == "__main__":
    asyncio.run(main())
